version: '3.7'
services:

    produtos:
        build: produtos

    calcados:
        build: calcados
        depends_on:
            - produtos

    vestuario:
        build: vestuario
        depends_on:
            - produtos

    nginx:
        container_name: nginx
        build: nginx
        ports:
            - 80:80
        depends_on:
           - produtos
           - calcados